#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
# exec 2>/dev/null
KEY="$1";
readonly ROOT=~/.config/sxiv

# Reads images into mapfile array
read_images() {
	mapfile -t images < <(tr '\n' '\0' | xargs -0 realpath)
}

# args: filenames to get tags from
# stdout: newline seperated list of tags
print_tags() {
	tmsu tags -1 "$@" | grep -v ':$\|^$' | sort -u
}

# args: files to get tags from, or all existing tags if no arguments
# vars: sets $tags to space seperated list of tags selected via rofi
# exit: with 1 if no tags selected, 0 otherwise
select_tags() {
	tags="$(print_tags "$@" | rofi -multi-select -dmenu | tr '\n' ' ')"
	[ "$tags" ]
}

# args: files to get tags from, or all existing tags if no arguments
# vars: sets tag to selected tag
# exit: with 1 if tag is selected, 0 otherwise
select_tag() {
	tag="$(print_tags "$@" | rofi -dmenu)"
	[ "$tag" ]
}

tag_add() {
	read_images
	(
		cd "$(dirname -- "${images[0]}")"
		while select_tags
		do tmsu tag --tags="$tags" "${images[@]}"
		done &
	)
}

tag_rm() {
	read_images
	(
		cd "$(dirname -- "${images[0]}")"
		local tags
		while select_tags --explicit "${images[@]}"
		do tmsu untag --tags="$tags" "${images[@]}"
		done &
	)
}

readonly YANKTAG="$ROOT"/yanktag

tag_yank() {
	local image
	read image
	printf "$image" > "$YANKTAG"
}

tag_paste() {
	read_images
	(
		cd "$(dirname -- "${images[0]}")"
		tmsu tag --from "$(cat "$YANKTAG")" "${images[@]}"
	)
}

readonly TAGFILE="$ROOT"/quicktags

# arg1: quick tag to set, must be a digit
set_quicktag() {
	local image
	read image
	(
		cd "$(dirname -- "$image")"
		local tag
		if select_tag
		then
			{
				grep -Fv "quicktag[$1]" "$TAGFILE" 2>/dev/null
				echo "quicktag[$1]='$tag'"
			} > "$TAGFILE.$$"
			mv "$TAGFILE.$$" "$TAGFILE"
		fi &
	)
}

# arg1: quick tag to use, must be a digit
use_quicktag() {
	read_images
	source "$TAGFILE"
	(
		cd "$(dirname -- "${images[0]}")"
		tmsu tag --tags="${quicktag[$1]}" "${images[@]}"
	)
}
shell() {
	read image
	"$TERMINAL" -cd "$(realpath "$(dirname -- "$image")")"
}

readonly LASTKEY=~/.config/sxiv/lastkey
if [ "$KEY" = "C-x" ]
then read KEY < "$LASTKEY"
fi

case "$KEY" in
"y") tag_yank ;;
"p") tag_paste ;;
"t") tag_add ;;
"T") tag_rm  ;;

"1") use_quicktag 1 ;; "exclam")      set_quicktag 1 ;;
"2") use_quicktag 2 ;; "at")          set_quicktag 2 ;;
"3") use_quicktag 3 ;; "numbersign")  set_quicktag 3 ;;
"4") use_quicktag 4 ;; "dollar")      set_quicktag 4 ;;
"5") use_quicktag 5 ;; "percent")     set_quicktag 5 ;;
"6") use_quicktag 6 ;; "asciicircum") set_quicktag 6 ;;
"7") use_quicktag 7 ;; "ampersand")   set_quicktag 7 ;;
"8") use_quicktag 8 ;; "asterisk")    set_quicktag 8 ;;
"9") use_quicktag 9 ;; "parenleft")   set_quicktag 9 ;;
"0") use_quicktag 0 ;; "parenright")  set_quicktag 0 ;;

"colon") shell ;;
 * )
	# echo no handler for "'$KEY'" >&2
	exit 0
	;;
esac

echo "$KEY" > "$LASTKEY"
