#!/usr/bin/env bash
#TODO better tags/layouts/etc
cmds=()
hc() { cmds+=(";" "$@"); }
Mod=Mod4 # use Super as modifier key

hc emit_hook reload
#{{{ theme
hc set frame_bg_transparent 1
hc attr theme.reset 1
hc attr theme.active.color     '#333366'
hc attr theme.normal.color     '#111122'
hc attr theme.urgent.color     '#884444'
hc attr theme.background_color '#222244'
hc attr theme.border_width 4
hc attr theme.floating.border_width 8
hc set frame_border_normal_color '#222244'
hc set frame_border_active_color '#333366'

hc set always_show_frame 0
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set window_gap 4
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 5

hc set tree_style '╾│ ├└╼─┐'
#}}}
#{{{ keybinds
hc keyunbind --all
hc keybind "$Mod-Shift-q" close
hc keybind "$Mod-Shift-r" reload
hc keybind "$Mod-Return"  spawn ${TERMINAL:-xterm}
hc keybind "$Mod-d"       spawn dmenu-launch

hc keybind XF86ScreenSaver      spawn slock
hc keybind XF86AudioMute        spawn amixer set Master toggle
hc keybind XF86AudioLowerVolume spawn amixer set Master 8%-
hc keybind XF86AudioRaiseVolume spawn amixer set Master 8%+
hc keybind XF86AudioPlay        spawn mpc toggle
hc keybind XF86AudioNext        spawn mpc next
hc keybind XF86AudioPrev        spawn mpc prev

hc keybind "$Mod-Left"      focus left
hc keybind "$Mod-Down"      focus down
hc keybind "$Mod-Up"        focus up
hc keybind "$Mod-Right"     focus right
hc keybind "$Mod-h"         focus left
hc keybind "$Mod-j"         focus down
hc keybind "$Mod-k"         focus up
hc keybind "$Mod-l"         focus right
hc keybind "$Mod-c"         cycle
hc keybind "$Mod-Tab"       cycle_all +1
hc keybind "$Mod-Shift-Tab" cycle_all -1
hc keybind "$Mod-i"         jumpto urgent
hc keybind "$Mod-BackSpace" cycle_monitor

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc keybind "$Mod-Shift-Left"  shift left
hc keybind "$Mod-Shift-Down"  shift down
hc keybind "$Mod-Shift-Up"    shift up
hc keybind "$Mod-Shift-Right" shift right
hc keybind "$Mod-Shift-h"     shift left
hc keybind "$Mod-Shift-j"     shift down
hc keybind "$Mod-Shift-k"     shift up
hc keybind "$Mod-Shift-l"     shift right

resizestep=0.05
hc keybind "$Mod-Control-h" resize left  "+$resizestep"
hc keybind "$Mod-Control-j" resize down  "+$resizestep"
hc keybind "$Mod-Control-k" resize up    "+$resizestep"
hc keybind "$Mod-Control-l" resize right "+$resizestep"

resizestep=0.1
hc keybind "$Mod-Control-Left"  resize left  "+$resizestep"
hc keybind "$Mod-Control-Down"  resize down  "+$resizestep"
hc keybind "$Mod-Control-Up"    resize up    "+$resizestep"
hc keybind "$Mod-Control-Right" resize right "+$resizestep"

hc keybind "$Mod-v" split right 0.5
hc keybind "$Mod-b" split bottom 0.5

hc keybind "$Mod-period" use_index +1 --skip-visible
hc keybind "$Mod-comma"  use_index -1 --skip-visible

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
#}}}
#{{{ tags
tags=(1:term 2:media 3:www)
tags+=(8:doc 9:anki 0:www)
hc silent rename default "${tags[0]}"
for tag in "${tags[@]}" ; do
	key="${tag:0:1}"
	hc add "$tag"
	hc keybind "$Mod-$key" use "$tag"
	hc keybind "$Mod-Shift-$key" move "$tag"
done
#}}}
#{{{ rules
hc unrule -F
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule focus=on # normally focus new clients
hc rule class=feh pseudotile=on tag=2:media
hc rule class=mpv tag=2:media
hc rule class=Sxiv pseudotile=on tag=2:media
hc rule class=Anki tag=9:anki
hc rule class=Firefox tag=0:www
hc rule class="Pale moon" tag=0:www
hc rule class=MuPDF tag=8:doc
hc rule class=llpp tag=8:doc
hc rule class=zathura tag=8:doc

#}}}
#{{{ Monitors
hc set swap_monitors_to_get_tag 0
hc detect_monitors
#}}}
#{{{ Panel
herbstclient chain "${cmds[@]}"

# start panel on every monitor
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
#}}}
# vim: foldmethod=marker foldmarker={{{,}}}
