#!/bin/bash
# TODO fix this mess

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
/usr/bin/xdg-user-dirs-update

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#Load xresource file
[[ -f ~/.config/X11/Xresources ]] && xrdb -merge ~/.config/X11/Xresources
[[ -f ~/.config/X11/urxvt      ]] && xrdb -merge ~/.config/X11/urxvt
## swap caps and escape, and let caps be used as Ctrl when pressed with another
[[ -f ~/.config/X11/Xmodmap    ]] && xmodmap     ~/.config/X11/Xmodmap
xcape -e 'Control_L=Escape;Control_R=Escape'

#Japanese input
export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'
hash uim-xim 2>/dev/null   && uim-xim &
export XMODIFIERS='@im=uim'
# programs
[ -x ~/.fehbg ]            && ~/.fehbg &
hash xrandr 2>/dev/null    && xrandr --output LVDS1 --left-of VGA1 &
hash xflux 2>/dev/null     && xflux -l 49 &
hash nm-applet 2>/dev/null && nm-applet &

xset -b on # enable bell
exec i3
