#!/bin/sh
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor VGA1  -d 6 7 8 9 0
# LVDS1 is main monitor
#bspc wm -O LVDS1 VGA1

bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          any
# Move pointer to monitor when changing focus
bspc config pointer_follows_monitor true
bspc config swallow_first_click     true
# Make windows fill entire node
bspc config honor_size_hints        false
bspc config ignore_ewmh_focus       true

bspc config normal_border_color   '#110000'
bspc config active_border_color   '#221111'
bspc config focused_border_color  '#663333'
bspc config presel_feedback_color '#663333'

bspc rule -a 'XFontSel' state=floating
bspc rule -a '*:risk of rain.exe' state=floating
bspc rule -a 'Zathura'  state=tiled
bspc rule -a 'Qjoypad'  state=floating

# Overlapping borders

width=1
bspc config border_width 1
bspc config window_gap  -1
for side in top bottom right left ; do
	bspc config ${side}_padding $width
done
exec sxhkd
