#!/bin/sh
bspc monitor LVDS1 -d 一 二 三 四 五
bspc monitor VGA1  -d 六 七 八 九 十

bspc config split_ratio             0.52
bspc config single_monocle          false
bspc config borderless_monocle      false
bspc config paddingless_monocle     false
bspc config gapless_monocle         false
bspc config click_to_focus          any
# Move pointer to monitor when changing focus
bspc config pointer_follows_monitor true
bspc config swallow_first_click     true
# Make windows fill entire node
bspc config honor_size_hints        false

bspc config normal_border_color   '#000011'
bspc config active_border_color   '#111122'
bspc config focused_border_color  '#333366'
bspc config presel_feedback_color '#333366'

bspc rule -a 'XFontSel' state=floating
bspc rule -a 'Zathura'  state=tiled

# Overlapping borders
width=5
bspc config border_width $width
bspc config window_gap  -$width
for side in top bottom right left ; do
	bspc config ${side}_padding $width
done
MONITOR=LVDS1 polybar bar &
MONITOR=VGA1  polybar bar &
exec sxhkd
